[package]
name = "aoc_2021"
version = "0.1.0"
authors = ["lloydmeta <lloydmeta@gmail.com>"]
edition = '2018'

[dependencies]
clap = "2.33"
itertools = "0.10"
combine = "4.4"
anyhow = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
